server:
  port: 8022
spring:
  application:
    name: rabbit-consumer-two
  profiles:
    active: dev
  rabbitmq:
    host: localhost
    port: 5672
    username: root
    password: root
#    virtual-host: my_host
#    requested-heartbeat: 20
#    publisher-returns: true
#    connection-timeout: 0
logging:
  config: classpath:logback-spring-dev.xml