server:
  port: 8021
spring:
  application:
    name: rabbit-consumer-one
  profiles:
    active: dev
  rabbitmq:
    host: 39.108.87.253
    port: 5672
    username: guest
    password: guest
#    virtual-host: my_host
#    requested-heartbeat: 20
#    publisher-returns: true
#    connection-timeout: 0
logging:
  config: classpath:logback-spring-dev.xml